Frontend/Controllers/DevicesController.cs
using Frontend.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text.Json;
using System.Text;
using System.Reflection;
using Frontend.HttpRequests;

namespace Frontend.Controllers
{
    public class DevicesController : Controller
    {
        private readonly HttpClient _httpClient;
        GenericRequests<Devices> genericRequestsDevices = new GenericRequests<Devices>();

        public DevicesController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public async Task<IActionResult> Index()
        { 
            try
            {
              var devicesList  = await genericRequestsDevices.GetListHttpRequest(":5191/api/Devices/get-device");
                GenericRequests<Packets> genericRequestsPackets = new GenericRequests<Packets>();
              var pakets=  await genericRequestsPackets.GetListHttpRequest(":5191/api/Packets/get-packet");
                //string apiUrl = "http://78.111.111.81:5191/api/Devices/get-device";
                //var response = await _httpClient.GetAsync(apiUrl);
                //string apiUrlPacket = "http://78.111.111.81:5191/api/Packets/get-packet";
                //var responsePacket = await _httpClient.GetAsync(apiUrlPacket);
                //if (response.IsSuccessStatusCode)
                //{
                //    var jsonResponse = await response.Content.ReadAsStringAsync();
                //    var model = System.Text.Json.JsonSerializer.Deserialize<List<Devices>>(jsonResponse, new JsonSerializerOptions
                //    {
                //        PropertyNameCaseInsensitive = true
                //    });
                //    var jsonResponsePacket = await responsePacket.Content.ReadAsStringAsync();
                //    var modelPacket = System.Text.Json.JsonSerializer.Deserialize<List<Packets>>(jsonResponsePacket, new JsonSerializerOptions
                //    {
                //        PropertyNameCaseInsensitive = true
                //    });
                //    return View(Tuple.Create(devicesList, pakets));
                //}
                //else
                //{
                //    ViewBag.ErrorMessage = "There was an error fetching data from the API.";
                //    return View(new List<Devices>());
                //}
                return View(Tuple.Create(devicesList, pakets));
            }
            catch (Exception ex)
            {

                return View("Erorr");
            }


        }
        [HttpPost]
        public async Task Create([FromBody] Devices brand)
        {
            if (ModelState.IsValid)
            {
                //var jsonData = JsonConvert.SerializeObject(brand);
                //var content = new StringContent(jsonData, Encoding.UTF8, "application/json");
                //await _httpClient.PostAsync("http://78.111.111.81:5191/api/Devices/create-device", content);

               await genericRequestsDevices.PostRequestGeneric(":5191/api/Devices/create-device",brand);
            }


        }
        [HttpPost]
        public async Task Update([FromBody] Devices brand)
        {
            if (ModelState.IsValid)
            {
                //var jsonData = JsonConvert.SerializeObject(brand);
                //var content = new StringContent(jsonData, Encoding.UTF8, "application/json");
                //await _httpClient.PutAsync("http://78.111.111.81:5191/api/Devices/update-device", content);
                 await genericRequestsDevices.UpdateRequestGeneric(":5191/api/Devices/update-device", brand);
            }


        }
        [HttpPost]
        public async Task Delete([FromBody] int id)
        {
            if (ModelState.IsValid)
            {
               // await _httpClient.DeleteAsync("http://78.111.111.81:5191/api/Devices/delete-device/" + id);
                await genericRequestsDevices.DeleteRequestGeneric(":5191/api/Devices/delete-device/",id);
            }
        }
    }
}

Frontend/Controllers/PacketController.cs
using Frontend.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text.Json;
using System.Text;
using Frontend.HttpRequests;
using System.Reflection;

namespace Frontend.Controllers
{
    public class PacketController : Controller
    {
        private readonly HttpClient _httpClient;
        GenericRequests<Packets> genericRequestsPacket = new GenericRequests<Packets>();
        public PacketController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
            var packets =  await genericRequestsPacket.GetListHttpRequest(":5191/api/Packets/get-packet");
                //string apiUrl = "http://localhost:5191/api/Packets/get-packet";
                //var response = await _httpClient.GetAsync(apiUrl);
                //if (response.IsSuccessStatusCode)
                //{
                //    var jsonResponse = await response.Content.ReadAsStringAsync();
                //    var model = System.Text.Json.JsonSerializer.Deserialize<List<Packets>>(jsonResponse, new JsonSerializerOptions
                //    {
                //        PropertyNameCaseInsensitive = true
                //    });
                //    return View(model);
                //}
                //else
                //{
                //    ViewBag.ErrorMessage = "There was an error fetching data from the API.";
                //    return View(new List<Packets>());
                //}
                return View(packets);
            }
            catch (Exception ex)
            {

                return View("Erorr");
            }


        }
        [HttpPost]
        public async Task Create([FromBody] Packets brand)
        {
            if (ModelState.IsValid)
            {
                //var jsonData = JsonConvert.SerializeObject(brand);
                //var content = new StringContent(jsonData, Encoding.UTF8, "application/json");
                //await _httpClient.PostAsync("http://localhost:5191/api/Packets/create-packet", content);
                await genericRequestsPacket.PostRequestGeneric(":5191/api/Packets/create-packet", brand);

            }


        }
        [HttpPost]
        public async Task Update([FromBody] Packets brand)
        {
            if (ModelState.IsValid)
            {
                //var jsonData = JsonConvert.SerializeObject(brand);
                //var content = new StringContent(jsonData, Encoding.UTF8, "application/json");
                //await _httpClient.PutAsync("http://localhost:5191/api/Packets/update-packet", content);
               await genericRequestsPacket.UpdateRequestGeneric(":5191/api/Packets/update-packet" , brand);

            }


        }
        [HttpPost]
        public async Task Delete([FromBody] int id)
        {
            if (ModelState.IsValid)
            {
              //  await _httpClient.DeleteAsync("http://localhost:5191/api/Packets/delete-driver/" + id);
               await genericRequestsPacket.DeleteRequestGeneric(":5191/api/Packets/delete-driver/" , id);
            }
        }
    }
}

Frontend/Views/Shared/_Footer.cshtml
<footer class="footer text-center text-sm-start">
    &copy; <script>
               document.write(new Date().getFullYear())
    </script> Uwingo Araç Takip Sistemleri <span class="text-muted d-none d-sm-inline-block float-end">
        Crafted with <i class="mdi mdi-heart text-danger"></i> by Uwingo Academy
    </span>
</footer><!--end footer-->

Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Uwingo Araç Takip Sistemleri Yönetim</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- App favicon Değişecek Logo -->
    
    <link rel="shortcut icon" href="~/images/uwingo.ico">
    @RenderSection("Styles", false)
    <link href="~/lib/sweet-alert2/sweetalert2.min.css" rel="stylesheet" type="text/css">
    <link href="~/lib/animate/animate.css" rel="stylesheet" type="text/css">
    <!-- App css -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/metisMenu.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/app.min.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/daterangepicker/daterangepicker.css" rel="stylesheet" type="text/css" />


    <link href="~/lib/datatables/dataTables.bootstrap5.min.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/datatables/buttons.bootstrap5.min.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/datatables/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />
</head>

<body class="">
    <!-- Left Sidenav -->
    <partial name="_Sidebar"></partial>
    <!-- end left-sidenav-->

    <div class="page-wrapper">
        <!-- Top Bar Start -->
        <div class="topbar">
            <!-- Navbar -->
            <nav class="navbar-custom">
                <ul class="list-unstyled topbar-nav float-end mb-0">
                    <li class="creat-btn">
                        <partial name="_SelectLanguage" />
                    </li>
                    <li class="dropdown">
                        <a class="nav-link dropdown-toggle waves-effect waves-light nav-user" data-bs-toggle="dropdown" href="#" role="button"
                           aria-haspopup="false" aria-expanded="false">
                            <span class="ms-1 nav-user-name hidden-sm">@Localizer["Uwingo Admin"]</span>
                            <img src="~/images/uwingo.ico" alt="profile-user" class="rounded-circle thumb-xs" />
                        </a>
                        <div class="dropdown-menu dropdown-menu-end">
                            <a class="dropdown-item" href="#"><i data-feather="user" class="align-self-center icon-xs icon-dual me-1"></i>@Localizer["Profile"]</a>
                            <a class="dropdown-item" href="#"><i data-feather="settings" class="align-self-center icon-xs icon-dual me-1"></i> @Localizer["Settings"]</a>
                            <div class="dropdown-divider mb-0"></div>
                            <a class="dropdown-item" href="#"><i data-feather="power" class="align-self-center icon-xs icon-dual me-1"></i> @Localizer["Logout"]</a>
                        </div>
                    </li>
                </ul><!--end topbar-nav-->

                <ul class="list-unstyled topbar-nav mb-0">
                    <li>
                        <button class="nav-link button-menu-mobile">
                            <i data-feather="menu" class="align-self-center topbar-icon"></i>
                        </button>
                    </li>
                </ul>
            </nav>
            <!-- end navbar-->
        </div>
        <!-- Top Bar End -->
        <div class="page-content">
            <!-- Page Content-->
            @RenderBody()

            <partial name="_Footer"></partial>
        </div>
        <!-- end page content -->
    </div>
    <!-- end page-wrapper -->
    <!-- jQuery  -->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/metismenu.min.js"></script>
    <script src="~/js/waves.js"></script>
    <script src="~/js/feather.min.js"></script>
    <script src="~/js/simplebar.min.js"></script>
    <script src="~/js/moment.js"></script>
    <script src="~/lib/daterangepicker/daterangepicker.js"></script>




    @RenderSection("scripts", false)
    <!-- App js -->
    <script src="~/js/app.js"></script>
    <script src="~/lib/sweet-alert2/sweetalert2.min.js"></script>
    <script src="~/js/pages/jquery.sweet-alert.init.js"></script>





    <script src="~/lib/datatables/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/dataTables.bootstrap5.min.js"></script>
    <script src="~/lib/datatables/dataTables.buttons.min.js"></script>
    <script src="~/lib/datatables/buttons.bootstrap5.min.js"></script>
    <script src="~/lib/datatables/jszip.min.js"></script>
    <script src="~/lib/datatables/pdfmake.min.js"></script>
    <script src="~/lib/datatables/vfs_fonts.js"></script>
    <script src="~/lib/datatables/buttons.html5.min.js"></script>
    <script src="~/lib/datatables/buttons.print.min.js"></script>
    <script src="~/lib/datatables/buttons.colVis.min.js"></script>
    <script src="~/lib/datatables/dataTables.responsive.min.js"></script>
    <script src="~/lib/datatables/responsive.bootstrap4.min.js"></script>
    <script src="~/js/pages/jquery.datatable.init.js"></script>
    <script src="~/js/alert/create.js"></script>
    <script src="~/js/alert/delete.js"></script>
    <script src="~/js/alert/update.js"></script>
</body>
</html>

Frontend/Views/Shared/_Maps.cshtml
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
      integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
      crossorigin="" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
        crossorigin=""></script>
<select id="num" class="form-select">
    <!-- 1'den 18'e kadar olan seçenekler -->
    <option value="13" disabled selected>@Localizer["Harita Görünümü"]</option>
    <option value="1">@Localizer["Tüm Dünya Görünümü"]</option>
    <option value="5">@Localizer["Ülke Görünümü"]</option>
    <option value="13">@Localizer["Şehir Görünümü"]</option>
    <option value="18">@Localizer["Sokak Görünümü"]</option>
</select>
<div id="map" style="height: 360px; position: relative; z-index: 1;"></div>
<script>
    let maxLatitude, minLongitude;
    var map = L.map('map').setView([0, 0], 1);
    let data = null;
    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    var markers = L.layerGroup().addTo(map);

    async function setData() {
        try {
            let response = await fetch('/TarckingDataAcc/index'); 
            data = await response.json();
            maxLatitude = -Infinity;
            minLongitude = Infinity;

            var num = document.getElementById("num").value;
            var intNum = parseInt(num, 10);
            data.forEach(item => {
                if (item.trackingDataForStd) {
                    if (item.trackingDataForStd.latitude > maxLatitude) {
                        maxLatitude = item.trackingDataForStd.latitude;
                    }
                    if (item.trackingDataForStd.longitude < minLongitude) {
                        minLongitude = item.trackingDataForStd.longitude;
                    }
                }
            });
            map.setView([maxLatitude, minLongitude], intNum);
            markers.clearLayers();
            fetchData();
        } catch (error) {
            console.error("Data fetch error:", error);
        }
    }

    document.getElementById("num").addEventListener("change", function () {
        var selectedValue = this.value;
        var intNum = parseInt(selectedValue, 10);
        map.setView([maxLatitude, minLongitude], intNum);
    });

    async function fetchData() {
        data.forEach(item => {
            if (item.trackingDataForStd) {
                var marker = L.marker([item.trackingDataForStd.latitude, item.trackingDataForStd.longitude])
                    .bindPopup(item.vehicles.plate);
                markers.addLayer(marker);
            }
        });
    }
    setData();
    setInterval(setData, 30000);
</script>

@*<script>
    debugger;
    let maxLatitude = -Infinity;
    let minLongitude = Infinity;
    var num = document.getElementById("num").value;
    var intNum = parseInt(num, 10);
    let data=null;
    var map = L.map('map');
    async function setData(){
        let response = await fetch('/TarckingDataAcc/index'); // API endpoint URL
        data = await response.json();
        var num = document.getElementById("num").value;
        var intNum = parseInt(num, 10);
        document.getElementById("num").addEventListener("change", function () {
            var selectedValue = this.value;
            intNum = parseInt(selectedValue, 10);
            map.setView([maxLatitude, minLongitude], intNum);
        });
        data.forEach(item => {
            debugger;
            if (item.trackingDataForStd) {
            if (item.trackingDataForStd.latitude > maxLatitude) {
                maxLatitude = item.trackingDataForStd.latitude;
            }
            if (item.trackingDataForStd.longitude < minLongitude) {
                minLongitude = item.trackingDataForStd.longitude;
            }
            }
        });
        map.setView([maxLatitude, minLongitude], intNum);
        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);//koordinatlar ve plakalar foreach
        fetchData();
    }
    setData();
    setInterval(function () {
        debugger;
        setData();
        var num = document.getElementById("num").value;
        var intNum = parseInt(num, 10);
        document.getElementById("num").addEventListener("change", function () {
            var selectedValue = this.value;
            intNum = parseInt(selectedValue, 10);
            map.setView([maxLatitude, minLongitude], intNum);
        });
        data.forEach(item => {
            debugger;
            if (item.trackingDataForStd) {
            if (item.trackingDataForStd.latitude > maxLatitude) {
                maxLatitude = item.trackingDataForStd.latitude;
            }
            if (item.trackingDataForStd.longitude < minLongitude) {
                minLongitude = item.trackingDataForStd.longitude;
            }
            }
        });
        map.setView([maxLatitude, minLongitude], intNum);
        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);//koordinatlar ve plakalar foreach
            fetchData();
    }, 30000);
        async function fetchData() {
            debugger;
            data.forEach(item => {
            if (item.trackingDataForStd) {
                var marker = L.marker([item.trackingDataForStd.latitude, item.trackingDataForStd.longitude]).addTo(map)
                    .bindPopup(item.vehicles.plate)
                    .openPopup();
            }
            });
        }

        //async function setData() {
        //    let response = await fetch('/TarckingDataAcc/index');
        //    if (!response.ok) {
        //        throw new Error('Network response was not ok');
        //    }
        //    let data = await response.json();

        //    data.forEach(item => {
        //        console.log("Alınan Son güncel veri :" + item.trackingDataForStd.serialNumber);
        //        debugger;
        //        // En büyük Latitude değerini bulma
        //        if (item.trackingDataForStd.latitude > maxLatitude) {
        //            maxLatitude = item.trackingDataForStd.latitude;
        //        }

        //        // En küçük Longitude değerini bulma
        //        if (item.trackingDataForStd.longitude < minLongitude) {
        //            minLongitude = item.trackingDataForStd.longitude;
        //        }
        //        map.setView([maxLatitude, minLongitude], intNum);
        //        console.log("Veri:" + item.trackingDataForStd);
        //        var latitude = item.trackingDataForStd.latitude || 0; // Varsayılan değer
        //        var longitude = item.trackingDataForStd.longitude || 0; // Varsayılan değer

        //        if (latitude !== 0 && longitude !== 0) {
        //            L.marker([latitude, longitude]).addTo(map)
        //                .bindPopup(item.vehicles.plate) // Dinamik içerik
        //                .openPopup();
        //        } else {
        //            console.error('Invalid data:', item);
        //        }
        //    });
        //};


        //let response = await fetch('/TarckingDataAcc/index');
        //if (!response.ok) {
        //    throw new Error('Network response was not ok');
        //}
        //let data = await response.json();
        //try {
        //    debugger;
        //    data.forEach(items => {
        //        debugger;
        //        if (items.trackingDataForStd.latitude > maxLatitude) {
        //            maxLatitude = items.trackingDataForStd.latitude;
        //        }

        //        // En küçük Longitude değerini bulma
        //        if (items.trackingDataForStd.longitude < minLongitude) {
        //            minLongitude = items.trackingDataForStd.longitude;
        //        }
        //    });
        //    map.setView([maxLatitude, minLongitude], intNum);
        //    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
        //        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        //    }).addTo(map);//koordinatlar ve plakalar foreach
        //    document.getElementById("num").addEventListener("change", function () {
        //        debugger;
        //        var selectedValue = this.value;
        //        intNum = parseInt(selectedValue, 10);
        //        map.setView([maxLatitude, minLongitude], intNum);
        //    });
        //} catch (error) {
        //    console.error('Fetch error:', error);
        //}
</script>*@

Frontend/Views/Shared/_SelectLanguage.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
<link href="~/assets/css/flag.css" rel="stylesheet" />
@inject IViewLocalizer localizer
@inject IOptions<RequestLocalizationOptions> options

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultures = options.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";

    var currentLanguage = requestCulture.RequestCulture.UICulture.Name switch
    {
        "tr-TR" => "TR",
        "en-US" => "EN",
        "kr-KR" => "KR",
        _ => "TR"
    };
}

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="languageDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        @currentLanguage
    </a>
    <div class="dropdown-menu" aria-labelledby="languageDropdown">
        <a class="dropdown-item" href="@Url.Action("SetLanguage", "Home", new { culture = "tr-TR", returnUrl = returnUrl })">Türkçe</a>
        <a class="dropdown-item" href="@Url.Action("SetLanguage", "Home", new { culture = "en-US", returnUrl = returnUrl })">English</a>
        <a class="dropdown-item" href="@Url.Action("SetLanguage", "Home", new { culture = "kr-KR", returnUrl = returnUrl })">Kurdî</a>
    </div>
</li>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var dropdown = document.getElementById('languageDropdown');
        dropdown.addEventListener('click', function () {
            var menu = dropdown.nextElementSibling;
            menu.classList.toggle('show');
        });
    });
</script>

Frontend/Views/Shared/_Sidebar.cshtml
<div class="left-sidenav">
    <!-- LOGO -->
    <div class="brand">
        <a asp-controller="home" asp-action="index" style="position:relative; z-index:1;" class="logo">
            <span>
                <img src="~/images/uwingoLogo.jpg" alt="logo-small" class="logo-sm">
            </span>
  @*          <span>
                <img src="~/images/uwingologo.jpg" alt="logo-large" class="logo-lg logo-light">
                <img src="~/images/uwingologo.jpg" alt="logo-large" class="logo-lg logo-dark">
            </span>*@
        </a>
    </div>
    <!--end logo-->
    <div class="menu-content h-100"  style="position:relative; z-index:2;" data-simplebar>
        <ul class="metismenu left-sidenav-menu">
            <li class="menu-label mt-0">@Localizer["Main"]</li>
            <li>
                <a href="javascript: void(0);"> <i data-feather="home" class="align-self-center menu-icon"></i><span>@Localizer["Dashboard"]</span><span class="menu-arrow"><i class="mdi mdi-chevron-right"></i></span></a>
                <ul class="nav-second-level" aria-expanded="false">
                    <li class="nav-item"><a class="nav-link" asp-controller="home" asp-action="index"><i class="ti-control-record"></i>@Localizer["Ana Sayfa"]</a></li>
                 
                </ul>
            </li>
            <li>
                <a href="javascript: void(0);"><i data-feather="file-plus" class="align-self-center menu-icon"></i><span>@Localizer["Sayfalar"]</span><span class="menu-arrow"><i class="mdi mdi-chevron-right"></i></span></a>
                <ul class="nav-second-level" aria-expanded="false">
                    <li class="nav-item"><a class="nav-link" asp-action="index" asp-controller="Vehicles"><i class="ti-control-record"></i>@Localizer["Araçlar"]</a></li>
                    <li class="nav-item"><a class="nav-link" asp-action="index" asp-controller="Devices"><i class="ti-control-record"></i>@Localizer["Cihazlar"]</a></li>
                    <li class="nav-item"><a class="nav-link" asp-action="index" asp-controller="Drivers"><i class="ti-control-record"></i>@Localizer["Sürücüler"]</a></li>
                    <li class="nav-item"><a class="nav-link" asp-action="index" asp-controller="DeviceVehicles"><i class="ti-control-record"></i>@Localizer["Cihaz'a Bağlı Araçlar"]</a></li>
                    <li class="nav-item"><a class="nav-link" asp-action="index" asp-controller="DriverVehicle"><i class="ti-control-record"></i>@Localizer["Sürücü'ye Bağlı Araç"]</a></li>
                    <li class="nav-item"><a class="nav-link" asp-action="index" asp-controller="Packet"><i class="ti-control-record"></i>@Localizer["Paketler"]</a></li>
                    <li class="nav-item"><a class="nav-link" asp-action="index" asp-controller="PacketContent"><i class="ti-control-record"></i>@Localizer["Paket İçerikleri"]</a></li>
                    <li class="nav-item"><a class="nav-link" asp-action="index" asp-controller="PeriodicMaintenance"><i class="ti-control-record"></i>@Localizer["Araç Bakım"]</a></li>
                    <li class="nav-item"><a class="nav-link" asp-action="TrackingIndex" asp-controller="TarckingDataAcc"><i class="ti-control-record"></i>@Localizer["Araç Takip Verileri"]</a></li>
                    @*<li class="nav-item"><a class="nav-link" asp-action="index" asp-controller="TrackingDataStd"><i class="ti-control-record"></i>İzleme Verileri Paket STD</a></li>*@
                   
                </ul>
            </li>
        </ul>

        <div class="update-msg text-center">
            <a href="javascript: void(0);" class="float-end close-btn text-muted" data-dismiss="update-msg" aria-label="Close" aria-hidden="true">
                <i class="mdi mdi-close"></i>
            </a>
            <h5 class="mt-3">@Localizer["Uwingo Academy"]</h5>
            <p class="mb-3">@Localizer["Uwingo Araç Takip Sistemleri Yönetim Paneli"]</p>
          
        </div>
    </div>
</div>